name: "Build and Deploy Next.js Application"
description: "Sets up Node.js, caches dependencies, installs them, runs tests, builds Next.js static files, and deploys."

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Next.js Application

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive  

      - name: Set up Node.js for client
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"
          cache: "npm"  # Enable caching for npm dependencies

      - name: Install client dependencies
        working-directory: ./client
        run: |
          echo "Installing client dependencies in $(pwd)"
          npm install --legacy-peer-deps

      - name: Run client tests
        working-directory: ./client
        run: |
          echo "Running client tests in $(pwd)..."
          npx jest

      - name: Build Next.js static files
        working-directory: ./client
        run: |
          echo "Building Next.js static files..."
          npm run build
          npm run export  # Export static files (if configured for static export)

      - name: Upload Next.js static files as artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-static-files
          path: ./out  # Assumes the static files are output to `out`

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Next.js static files
        uses: actions/download-artifact@v2
        with:
          name: nextjs-static-files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
