name: "Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧"
description: "Sets up Node.js, caches dependencies, and installs them."
runs:
  using: "composite"
  steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive  

    - name: Set up Node.js for client
      uses: actions/setup-node@v2
      with:
        node-version: "18.18.0"

    - name: Install client dependencies
      working-directory: client
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing files:"
        Get-ChildItem -Force
        npm install --legacy-peer-deps

    - name: Run client tests
      working-directory: client
      run: |
        echo "Running client tests..."
        npx jest

    - name: Set up Node.js for server
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Install server dependencies
      working-directory: server
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing files:"
        Get-ChildItem -Force
        npm install --legacy-peer-deps
