name: "Build and Deploy Next.js Application"
description: "Sets up Node.js, caches dependencies, installs them, runs tests, builds Next.js static files, and deploys."

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Next.js Application

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive  

      - name: Log current directory and list files
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Set up Node.js for client
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"
          cache: "npm"

      - name: Log Node.js version
        run: node -v

      - name: Install client dependencies
        working-directory: ./client
        run: |
          echo "Installing client dependencies in $(pwd)"
          npm install --legacy-peer-deps
          echo "List of files in $(pwd):"
          ls -la

      - name: Run client tests
        working-directory: ./client
        run: |
          echo "Running client tests in $(pwd)"
          npx jest
          echo "List of files after tests in $(pwd):"
          ls -la

      - name: Build Next.js static files
        working-directory: ./client
        run: |
          echo "Building Next.js static files in $(pwd)"
          npm run build
          npm run export
          echo "List of files in $(pwd)/out after export:"
          ls -la ./out

      - name: Upload Next.js static files as artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-static-files
          path: ./client/out

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Next.js static files
        uses: actions/download-artifact@v2
        with:
          name: nextjs-static-files

      - name: Log downloaded files
        run: |
          echo "List of files in downloaded artifact:"
          ls -la ./client/out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/out
