name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-2022

    steps:
      # Step 1: Checkout code with submodules
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Initializes and updates submodules

      # Step 2: Client Setup
      - name: Set up Node.js for client
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"

      - name: Install client dependencies
        working-directory: client
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          Get-ChildItem -Force
          npm install --legacy-peer-deps

      - name: Run client tests
        working-directory: client
        run: |
          echo "Running client tests..."
          npx jest

      # Step 3: Server Setup
      - name: Set up Node.js for server
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install server dependencies
        working-directory: server
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          Get-ChildItem -Force
          npm install --legacy-peer-deps

      # Step 4: Deploy to Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
        run: |
          # Install Heroku CLI
          curl https://cli-assets.heroku.com/install.sh | sh
          # Authenticate using the API key
          heroku auth:token
          heroku git:remote -a your-heroku-app-name  # Replace with your Heroku app name
          # Push to Heroku
          git push heroku main
