name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive  # This initializes and updates submodules

      # Client Setup
      - name: Set up Node.js for client
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"

      - name: Install client dependencies
        working-directory: client
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          Get-ChildItem -Force
          npm install --legacy-peer-deps

      - name: Run client tests
        working-directory: client
        run: |
          echo "Running client tests..."
          npx jest

      # Server Setup
      - name: Set up Node.js for server
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install server dependencies
        working-directory: server
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          Get-ChildItem -Force
          npm install --legacy-peer-deps

      
