name: CI

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for client
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"

      - name: Install client dependencies
        run: |
          pwd
          ls -R
          cd client
          npm install

      - name: Run client tests
        run: |
          cd client
          npx jest

      - name: Set up Node.js for server
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install server dependencies
        run: |
          cd server
          npm install
